/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const NotifyPlugin: typeof import('tdesign-vue-next')['NotifyPlugin']
}
