/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Body: typeof import('./src/components/mcg-layout/body.vue')['default']
    ColorBar: typeof import('./src/components/color-picker/color-bar.vue')['default']
    ColorPicker: typeof import('./src/components/color-picker/color-picker.vue')['default']
    ColorQuickslot: typeof import('./src/components/color-picker/color-quickslot.vue')['default']
    Footer: typeof import('./src/components/mcg-layout/footer.vue')['default']
    Header: typeof import('./src/components/mcg-layout/header.vue')['default']
    HexInput: typeof import('./src/components/color-picker/hex-input.vue')['default']
    Main: typeof import('./src/components/color-picker/main.vue')['default']
    McgCard: typeof import('./src/components/mcg-card/mcg-card.vue')['default']
    Picker: typeof import('./src/components/color-picker/picker.vue')['default']
    PreviewBox: typeof import('./src/components/text-output/preview-box.vue')['default']
    TextInput: typeof import('./src/components/text-input/text-input.vue')['default']
    TextOutput: typeof import('./src/components/text-output/text-output.vue')['default']
    TextParams: typeof import('./src/components/text-params/text-params.vue')['default']
    ToolBar: typeof import('./src/components/text-params/tool-bar.vue')['default']
  }
}
