/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Body: typeof import('./src/components/mcg-layout/body.vue')['default']
    ColorBar: typeof import('./src/components/color-picker/color-bar.vue')['default']
    ColorPicker: typeof import('./src/components/color-picker/color-picker.vue')['default']
    ColorQuickslot: typeof import('./src/components/color-picker/color-quickslot.vue')['default']
    Footer: typeof import('./src/components/mcg-layout/footer.vue')['default']
    Header: typeof import('./src/components/mcg-layout/header.vue')['default']
    HexInput: typeof import('./src/components/color-picker/hex-input.vue')['default']
    McgCard: typeof import('./src/components/mcg-card/mcg-card.vue')['default']
    McgFeedback: typeof import('./src/components/mcg-feedback/mcg-feedback.vue')['default']
    Picker: typeof import('./src/components/color-picker/picker.vue')['default']
    PreviewBox: typeof import('./src/components/text-output/preview-box.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TextInput: typeof import('./src/components/text-input/text-input.vue')['default']
    TextOutput: typeof import('./src/components/text-output/text-output.vue')['default']
    TextParams: typeof import('./src/components/text-params/text-params.vue')['default']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLink: typeof import('tdesign-vue-next')['Link']
    ToolBar: typeof import('./src/components/text-params/tool-bar.vue')['default']
    TOption: typeof import('tdesign-vue-next')['Option']
    TPopconfirm: typeof import('tdesign-vue-next')['Popconfirm']
    TPopup: typeof import('tdesign-vue-next')['Popup']
    TRate: typeof import('tdesign-vue-next')['Rate']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TTextarea: typeof import('tdesign-vue-next')['Textarea']
  }
}
