/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ColorBar: typeof import('./src/components/color-picker/color-bar.vue')['default']
    ColorCube: typeof import('./src/components/color-picker/color-cube.vue')['default']
    ColorList: typeof import('./src/components/ColorList.vue')['default']
    ColorPicker: typeof import('./src/components/color-picker/index.vue')['default']
    ColorQuickslot: typeof import('./src/components/color-picker/color-quickslot.vue')['default']
    Footer: typeof import('./src/components/mcg-layout/footer.vue')['default']
    Header: typeof import('./src/components/mcg-layout/header.vue')['default']
    HexInput: typeof import('./src/components/color-picker/hex-input.vue')['default']
    Main: typeof import('./src/components/color-picker/main.vue')['default']
    McgFooter: typeof import('./src/components/mcg-layout/mcg-footer.vue')['default']
    McgHeader: typeof import('./src/components/mcg-layout/mcg-header.vue')['default']
    Picker: typeof import('./src/components/color-picker/picker.vue')['default']
    TAlert: typeof import('tdesign-vue-next')['Alert']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TDrawer: typeof import('tdesign-vue-next')['Drawer']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLink: typeof import('tdesign-vue-next')['Link']
    TPopconfirm: typeof import('tdesign-vue-next')['Popconfirm']
    TPopup: typeof import('tdesign-vue-next')['Popup']
    TRadio: typeof import('tdesign-vue-next')['Radio']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTextarea: typeof import('tdesign-vue-next')['Textarea']
  }
}
